name: build
on: 
  push: 
    branches: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          lerna bootstrap
          lerna run build
      - name: Deploy 🚀
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
         host: ${{ secrets.DR_HOST }}
         user: ${{ secrets.DR_USER }}
         pass: ${{ secrets.DR_PASS }}
         port: ${{ secrets.DR_PORT }}
         connect_timeout: 10s
         first_ssh: |
            rm -rf /usr/local/webserver/nginx/test
            mkdir -p /usr/local/webserver/nginx/test
         scp: |
           './packages/dooringx-example-vue3.0/dist/*' => /usr/local/webserver/nginx/test
        #  src: './dist/*'
        #  remote: /usr/local/webserver/nginx/html